# Numpy

In [1]:
import numpy as np

In [4]:
#creating numpy array
arr=np.array([[1,2,3,4],[5,6,7,8]])


In [5]:
type(arr)

numpy.ndarray

In [6]:
#dimension of array
print(arr.ndim)

2


In [7]:
#shape of array
print(arr.shape)

(2, 4)


In [8]:
#1d array
a=np.array([1,2,3,4])

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [14]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [12]:
arr2.shape

(3, 5)

In [13]:
arr2.ndim

2

In [15]:
#show memory location where data is stored
print(arr2.data)

# Random Number Generator using numpy

In [16]:
from numpy import random



In [21]:
x=random.randint(100)
print(x)

1


In [22]:
for i in range(0,5):
    print(random.randint(1000))

636
413
135
666
865


In [23]:
x=random.randint(1000)
y=random.randint(1000)
z=random.randint(1000)

In [24]:
print(x,y,z)

28 754 201


In [25]:
#float random no
x=random.rand()
print(x)

0.4945361030914466


In [26]:
for x in range(0,5):
    print(random.rand())

0.9454317470029789
0.58937478590023
0.9899544506677583
0.8712601408803423
0.9438368857023787


In [30]:
#generate random array
from numpy import random
x=random.randint(100,size=(5,7))
print(x)

[[91 50 87 63 93 69 24]
 [82 65 72 48 97 14 48]
 [ 4 48 33 93 77 48 10]
 [61 35 39 81 14 25 66]
 [46 39 89  4 94 37 40]]


In [32]:
x.shape


(5, 7)

In [33]:
x.ndim

2

# Measurement of central tendency


In [34]:
import numpy as np
arr=np.array([[1,2,3,],[98,99,100],[67,88,90]])
print(arr)
#min function 
print(np.amin(arr))
#max function
print(np.amax(arr))

[[  1   2   3]
 [ 98  99 100]
 [ 67  88  90]]
1
100


In [35]:
#finding mean,median,standard deviation and varaiance in Numpy
print(np.mean(arr))

60.888888888888886


In [36]:
#median 
np.median(arr)

88.0

In [37]:
#standard deviation
np.std(arr)

42.66782405837616

In [38]:
#variance
np.var(arr)

1820.5432098765434

# Array brodcasting using Numpy

In [39]:
# various operation btw. array can be said as broadcasting 
a=np.array([1.0,2.0,3.0])
b=np.array([4.0,5.0,6.0])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)

[5. 7. 9.]
[-3. -3. -3.]
[ 4. 10. 18.]
[0.25 0.4  0.5 ]
[0. 0. 0.]
